### ISSUE TITLE
Does this work ?

### ISSUE THREAD

**Issue by Karsten1987** [manekinekko/bbox-remote-control#1]
I find your repository absolutely interesting. I tried to run it, but I failed. I constantly see httprequest errors.
Did you manage to get your code to work and what would I have to change in order to make it work for my BBox?

So I got the commands running via CURL. Now I wonder if this upnp is only for the media center or can we actually change the TV channel via upnp?
Thanks a lot!

**Comment by manekinekko** [comment]
hi @Karsten1987 
Unfortunately, I dont maintain this repo anymore. I left this ISP many months ago. I dont have the BBOX setup box to test this code.

Please feel free to fork it if you still have the BBOX setup box.

However, can you submit a snippet of the error you're getting? Maybe I can help ^^
